### PR TITLE
Adding exception handling to gitversion

### PR DESCRIPTION
**Pull request by ethan-nelson**
Re: #652...custom installs sometimes cause `gitversion` to throw an error and not render the about page.

### CODE REVIEW

**Comment by Andygol** [comment]
I made this changes and get the next error:
```
[Sun Jun 21 10:08:57.739704 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/env/local/lib/python2.7/site-packages/Mako-1.0.1-py2.7.egg/mako/runtime.py", line 835, in _render_context
[Sun Jun 21 10:08:57.739707 2015] [:error]      _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
[Sun Jun 21 10:08:57.739709 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/env/local/lib/python2.7/site-packages/Mako-1.0.1-py2.7.egg/mako/runtime.py", line 860, in _exec_template
[Sun Jun 21 10:08:57.739712 2015] [:error]      callable_(context, *args, **kwargs)
[Sun Jun 21 10:08:57.739714 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/osmtm/templates/base.mako", line 108, in render_body
[Sun Jun 21 10:08:57.739717 2015] [:error]      
[Sun Jun 21 10:08:57.739719 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/osmtm/templates/about.mako", line 75, in render_content
[Sun Jun 21 10:08:57.739722 2015] [:error]      ${txt |n}
[Sun Jun 21 10:08:57.739724 2015] [:error]    UnboundLocalError: local variable 'txt' referenced before assignment
[Sun Jun 21 10:08:57.739727 2015] [:error]  
```

**Comment by Andygol** [comment]
@ethan-nelson ^^^

**Comment by ethan-nelson** [comment]
Ok I see the issue...I will refix and get back to you

**Comment by ethan-nelson** [comment]
I tested this latest fix with commenting out one of the variables to throw an exception and it seems to work now. cc: @Andygol

**Comment by Andygol** [comment]
Yeah! Working but not showing info about version
image

**Comment by batpad** [comment]
*bump* ran into this when upgrading a custom instance at http://tasks.openstreetmap.in

@ethan-nelson is this something you see being able to merge into `master` / anything I can help with?

**Comment by pgiraud** [comment]
@batpad we can add this workaround. Do you want this merged into master or in a 2.13.x stable release?

I'm not happy with the `gitversion` package by the way. I've used another technique recently.
See https://github.com/hotosm/osm-tasking-manager2/issues/652#issuecomment-205768476 and https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/__init__.py#L28-L32

**Comment by batpad** [comment]
@pgiraud `master` is fine - perhaps better not to put this workaround into a stable release if we feel we can do better?

This is not a huge deal / blocker for me or anything, whatever is better for the project - also happy to hold off until we have a better fix - just wanted to keep this on the radar since it's likely others will run into it as well :)

**Comment by pgiraud** [comment]
Thanks for your feedback.
I'm merging since it's just a quick fix to an annoying bug.

**Pull request merged**
