### PR TITLE
embed video in task description/ instruction

### PR DESCRIPTION
**Pull request by yiqingj**
for issue #721
this is to enable embedding video/image into task description/instruction by adding an oEmbed extension to python markdown library.  

this solution is coming from https://github.com/rennat/python-markdown-oembed  with a few bug fixes 

a sample markdown for Youtube:
```markdown
![video](http://www.youtube.com/watch?v=StTqXEQ2l-Y)
```

===== update======
also support the preview tab by updating showdown version and adding a youtube extension. 

@pyrog I just noticed that PR #527 also try to update showdown version and make all markdown client rendered.   if that's the case we could just add the js youtube extension in my PR and remove the python markdown extension.  Do a cherrypick or just let me know after you merge #572 so I could update my PR accordingly.

### CODE REVIEW

**Comment by dalekunce** [comment]
Brilliant!!

**Comment by pgiraud** [comment]
Thanks for this nice contribution!
I'll review this as soon as possible. Don't hesitate to hunt if I forget.

**Comment by pgiraud** [comment]
Your code looks nice. Can you please squash your commits into one?

**Comment by yiqingj** [comment]
created PR #739 with one commit for all changes as requested by @pgiraud. closing this one.

**Comment by pgiraud** [comment]
You didn't have to create a new pull request for that. You can squash/fixup commits and push force again your branch to the remote. It's worth to learn this nice feature. You'll find dedicated tutorials.

**Comment by aawiseman** [comment]
Hey guys, is this live yet? I tried it on task 1460 but it didn't work, I just got a missing image type box. Thanks.

**Comment by pgiraud** [comment]
Hi @aawiseman. Sorry, it's not live. I expect to do a release soon and get it on production.

**Comment by aawiseman** [comment]
@pgiraud ah thanks. Do you know when roughly? Just curious. Thanks!

**Comment by aawiseman** [comment]
@pgiraud hi Pierre, it still looks like it's not working, I just see a little box with a question mark. I'm looking at http://tasks.hotosm.org/project/1460 under the Instructions tab. Is the new version not line yet? Thanks!

**Comment by pgiraud** [comment]
@aawiseman sorry it's still not live. The release process takes a bit of time. Hopefully, we should be able to get this working live in the next days.
However, you can already test it on the dev instance.

**Comment by aawiseman** [comment]
@pgiraud Got it, thanks!

**Comment by pgiraud** [comment]
@aawiseman We finally managed to deploy the 2.12 release! It's now live.

**Comment by aawiseman** [comment]
@pgiraud woohoo! Thank you, it looks great!

**Pull request closed without merging**
