### PR TITLE
Combining lock/unlock events, with added duration

### PR DESCRIPTION
**Pull request by ethan-nelson**
This was harder than I thought to implement and it's by no means the neatest I imagine. I'm opening it up so all can test the code and provide any feedback. I haven't performed timing tests yet; with 25 log entries, there was no noticeable degradation of loading time due to the loop at the start.

As per discussion from #503 and others, this pull request has a few items of interest to note. 

1. Prior to the activity population, the history is looped to find matching cases where there is a lock event with ```X``` id and an unlock event with ```X+1``` id. 
2. ```div``` is applied deeper in the if statements. If a lock event has a matching unlock (i.e. if the tile is free for someone to lock), we can then completely ignore that log event instead of rendering an empty ```div``` section. We also move the timeago declaration further into the statements to prevent those from being printed where an unlock event is not added.
3. The ```"first"``` tag is applied to both the first and second loop iterations for the task activity log. This prevents an open top shape on the log if the first history item is an unlock event (which from 2. we know is null). No noticeable double-rendering on the top of the second activity item occurs. The same can't be said for the project activity tab, hence this definition only in the task area.
4. Lock activity log entries are changed to prevent ambiguity:
 * If the task is currently locked, the text now says ```Currently locked by {user}``` with the timeago below.
 * If the task has been unlocked, the text says ```Was locked by {user}``` with the timeago and duration below.
5. Duration is implemented in a quasi-fuzzy text fashion, with times over an hour being of the format ```for X hour, X minutes```.

New example images. First, during a state of locked.
newlock
Next during a state of unlock.
new2

### CODE REVIEW

**Comment by ethan-nelson** [comment]
One more comment....after I took the screenshots, I changed the code to say ```for {time}``` instead of ```after {time}``` on the locking events.

**Comment by althio** [comment]
I agree about your change 'after' >>> 'for' ;-)
My following comments are based also on your screenshots, I didn't run your code.

Did you choose on purpose to hide the comments when locked? I would rather say they are also useful then. >>> comments displayed when locked

Other very minor comment or suggestions:
**Currently** locked by ... : I agree :+1:
**Was** locked by ... >>> Previously locked by ...
Comment **left** by FTA >>> Comment by FTA

**Comment by ethan-nelson** [comment]
Comments don't hide when locked...I just didn't have a comment added until after that screenshot. I do like your word tweaks althio. Also found a minor optimization I put in.
extra new

**Comment by althio** [comment]
Thanks @ethan-nelson that is fine by me! :+1: 

FYI or for future reference I made a small research about timeago as an alternative, since it is already used in the project.
I can't judge if this is neat or easy to use it again for duration only. It would require apparently to use a second instance (if that makes sense?) and change the config with prefixAgo, prefixFromNow, suffixAgo, suffixFromNow and locales.
I don't know if that is more work or less work for implementation and localisation than your current proposal for this small bit of code.

default config:
```
  prefixAgo: null,
  prefixFromNow: null,
  suffixAgo: "ago",
  suffixFromNow: "from now",
```

for duration config:
```
  prefixAgo: "for",
  prefixFromNow: null,
  suffixAgo: null,
  suffixFromNow: null,
```

**Comment by ethan-nelson** [comment]
@althio that is probably the best way to go about it. I'll play around with it this evening and see if I can get it to work...my way is far from pretty.

**Comment by ethan-nelson** [comment]
@althio unfortunately timeago doesn't seem to work for time difference values...it only takes in a raw date/time string and calculates the time since. That said, I am going to take the calculation/creation of the string out of the python and push it into a function callable similar to timeago.

**Comment by ethan-nelson** [comment]
Pulling pull request for now to find elegant time difference solution.

**Pull request closed without merging**
