### PR TITLE
add 'default_comment_prefix' setting, add testing.setUp to get current tests working

### PR DESCRIPTION
**Pull request by batpad**
Refs #688 

@pgiraud If the implementation looks okay to you, I will add some tests for this and then hopefully can be merged. Thank you.

### CODE REVIEW

**Comment by pgiraud** [comment]
Sorry for not answering on this one.
This looks good to me.
However, since there are changes in the database model (new column added), we need alembic migration script so that database migration of already installed instance can be upgraded easily.

**Comment by batpad** [comment]
hey @pgiraud no problems - thanks for the response.

There is no db column added here - just an optional setting that can be added to `local.ini` to set a custom comment prefix. Unless I am missing something, this should not affect the db in any way?

What is needed is some documentation here plus some way to test this. I will add a couple of lines to the README and figure out a way to test custom settings and add commits to the PR.

**Comment by pgiraud** [comment]
My bad, I didn't read carefully.
Can you please add some documentation about it?
I'd like to have a version released this week and I'd be happy to see this feature in.
Let's forget the tests for now. We'll address it later on.

**Comment by batpad** [comment]
@pgiraud rebased branch to master and added a note in the README about the new setting. Please feel free re-word the documentation if it does not seem clear.

Let me know if you need anything further from me on this. All the best with the release.

**Comment by pgiraud** [comment]
Do the modifications on the tests required for the current pull request? If not, please remove them.
Also please squash your commits into one to make history simpler.

**Comment by batpad** [comment]
@pgiraud sorry for the delay here - squashed commits and pushed.

Unfortunately, the modifications to tests are required once the code is using `threadlocal` to get registry items from `local.ini`. http://docs.pylonsproject.org/projects/pyramid/en/latest/api/testing.html#pyramid.testing.setUp

I am quite inexperienced with Pyramid, though, so could well be missing something. I could not manage to get current tests to pass without making those changes, though.

There are a couple of things here that I might not have implemented in the best way due to not knowing Pyramid best practices. If you are unsure of any of those things, please feel free to hold off this merge until next release / until we are more sure of what we are doing here. Thanks.

**Comment by pgiraud** [comment]
OK. This looks good to me. Thanks for this great addition.

**Pull request merged**
