### PR TITLE
Add support for labels for projects

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by pgiraud** [comment]
This pull request follows initial work done by @ethan-nelson on https://github.com/hotosm/osm-tasking-manager2/pull/819

### Label vs. tag

The name "label" was preferred over "tag" since the keywords are predefined by administrators. This is not a list where anyone can put anything.

### Database backend

A new table is created for storing labels and the translatable description associated to the label.
Labels can be given a color and their name can contain blank spaces.

### Editing

Project managers can add/remove/edit labels.

### Tag assignment

Project managers can assign labels to the projects.

### Search

Label search is available via the url parameter `labels=x+y+z+...`. For labels with white spaces double quotes need to be added. `labels="my+label"+"an+other+label"`

Users can also use the new dropdown menu.

### Description

If one or more labels are searched, the description for each label appears on the right hand side of the screen.

### New projects list page

The projects search now appears in its own dedicated page.
On the home page are displayed the top 5 projects (sorted by priority).


Temporary demo is available here http://tasks-hotosm.dev.sig.cloud.camptocamp.net/tagging
Any feedback is welcome.

**Comment by ethan-nelson** [comment]
I'll take a look later today and provide any feedback!

**Comment by bgirardot** [comment]
Let us not change the layout of the front page so much. Filtering by tags and displaying the tags is good. the rest of the changes to the front page need to be planned out more.

**Comment by pgiraud** [comment]
> The only tiny bug I see is when editing the labels, if you click on a label, not the edit link, but a label, it does kind of search for projects with that label, but the url is mis formed so it returns zero results.

Fixed. Demo updated.

**Comment by RAytoun** [comment]
Hi Pierre, Blake,
This looks really great and adds a bit more ‘sophistication’ to the page. Highlighting the aid agencies involved gives quite a bit more credence to the concept of humanitarian work and helps the search for projects and compilation of statistics.
Is there some way that more emphasis can be given to a disaster activation as opposed to a Missing Maps project? Like a highlighter background to the title of the project, that will make it obviously stand out as the urgency is “right now” rather than priority? Wish I knew something about programming so I can give you guys a hand.
Creating better tools to work with leads to far more people wanting to continue mapping. Great work.

**Comment by pgiraud** [comment]
As asked by @bgirardot I changed my pull request to keep the home page as it was (ie. not providing a new page dedicated to the projects list).
http://tasks-hotosm.dev.sig.cloud.camptocamp.net/labels/?labels=%22Missing+Maps%22

**Comment by RAytoun** [comment]
Hi Pierre, Blake and all,

I have had a look at the link to the example and I was first taken aback that it did not open on the full list that was usually available. I am in favour of still having the original opening page but the drop down filter can be used by those who need to separate out the projects. I like that the disaster button that immediately clears away all the other projects which means that I can quickly check whether there is a disaster activation that needs immediate attention before starting to look at the other projects and would like to see that button at the top of the drop down list. What would also be helpful is a means to return to the unfiltered start page. I still think that it is a great idea and delighted that we are using drop down menus that give a better idea of what we have and a way of navigating to what we are looking for.
Thank you for the this so far.

**Comment by bgirardot** [comment]
The latest version looks great. The only adjustment i see being needed is an indication when something from the "filter" menu is selected, at the moment only "Your Projects".

Labels are well indicated, and the sort options are well indicated, just not the selection from the filter menu. I would not let it hold up deployment at all.

**Pull request merged**
