### PR TITLE
Allow only admins and project managers to access draft projects

### PR DESCRIPTION
**Pull request by ethan-nelson**
Re: #405, we check whether a project is a draft before rendering. If it is a draft, we have a two-tiered test:

1. Is a user logged in?
2. If so, are they an admin or project manager?

If at least one of these is no, we act in the same manner as if the project does not exist.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Looks like there are two tests failing. Investigating...

**Comment by ethan-nelson** [comment]
When the tests create a project, they must now publish them for general users to access them. So, I modified test_project to make this happen. nosetests is now successful.

**Comment by pgiraud** [comment]
@ethan-nelson Here's IMO a cleaner way to handle it (using permissions):
https://github.com/hotosm/osm-tasking-manager2/pull/629

**Comment by ethan-nelson** [comment]
Works for me

**Pull request closed without merging**
