### PR TITLE
Fix translation problem in mako template.

### PR DESCRIPTION
**Pull request by katelaurel**
Fix minor translation issue in #798 .

### CODE REVIEW

**Comment by pgiraud** [comment]
Hi @katelaurel, this is really good start. However this is not exactly what I was waiting for.

The following section of the template applies to the bottom part of the contribute tab.
https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/templates/task.history.mako#L49-L56
capture d ecran 2016-06-18 a 11 48 19

In this tab, we already are referring to a specific task (square) number.
So the sentence should still be "Marked as done by xxxxx". The result in the interface should not be changed.

But instead of translating "Marked as done" and "by" separately this should be done in the same block.
Does it make sense?

Same should be done for "Invalidated by", "Validated by" and "Split by".

**Comment by katelaurel** [comment]
Thanks, this is a helpful clarification (and the potential translation issues this could cause are pretty apparent...). I'll go back in and take care of these.

**Comment by pgiraud** [comment]
Hum, still not perfect.
The username variable should be included in the translated string and replaced using a mapping.
In other languages, we cannot be sure that the order of words within a sentence can be the same. ie. "Marked as done by MisterFoo" may not be translated with the username at the end of the sentence. This means that translating "Marked as done by" and adding the username after that may not make sense in other languages.

**Comment by pgiraud** [comment]
@katelaurel Still willing to push this pull request a bit further?
Is my last comment clear enough?

**Pull request closed without merging**
