### PR TITLE
Added Slovenian localization

### PR DESCRIPTION
**Pull request by stefanb**
...currently only to development as it is only 55% done (pulled from Transifex)

### CODE REVIEW

**Comment by pgiraud** [comment]
@dodobas Can you please give this pull request a review?

**Comment by skalca** [comment]
@pgiraud You are actually asking a croatian to review slovenian translation :) [it looks like from twitter that Mr. Odobašić lives in Zagreb]. 

I have read through the entire translation file and beside from some typos and wrong word ordering (and a loooot of missing translations) all looks well.

**Comment by stefanb** [comment]
The translation is not complete yet, it is work in progress. This is why I only included it in development config file, not the production one. 
We use review functionality in Transifex for the content and @skalca, you're welcome to join :)

**Comment by skalca** [comment]
Yeah, sorry, my bad. I only just now saw the "… only 55% done" comment at your commit.

A question. I would like to join in, but I need to ask about "transifex". This is the first time I hear about it, so my question is: *Do I need to use it, or do I just translate missing terms in "notepad" and commit the file?*

**Comment by stefanb** [comment]
@skalca, this is not my decision, but project-wide, as stated in [README.md](https://github.com/hotosm/osm-tasking-manager2/blob/master/README.md)
Setting up sync from [Transifex](https://www.transifex.com/projects/p/osm-tasking-manager2/) to git is fairly easy, doing it both ways is prone to conflicts.

**Comment by skalca** [comment]
@stefanb Thanks, I need to re-read stuff... I missed that one.

**Comment by skalca** [comment]
I have completely translated *master* to slovenian. @stefanb please make a pull request if you think everything is ok.

**Comment by stefanb** [comment]
@skalca, your translations seem fine, so I added the changes to this pull request. Thanks!

**Comment by stefanb** [comment]
Are there any reasons for not using this?

**Comment by dodobas** [comment]
@stefanb when I saw this PR, my first thought was, "oh, I need to sync this with transifex" and that requires more time than just clicking 'Merge pull request' :)

I'll do it tomorrow...

**Comment by stefanb** [comment]
Changes to Slovenian translation were pulled from transifex and are included in this patch. I didn't commit other languages to keep the patch clean.

**Comment by pgiraud** [comment]
@dodobas Can you please make it so we can merge this?

**Comment by stefanb** [comment]
Was it rejected for any specific reason?

**Comment by dodobas** [comment]
no, it's accepted, just not pushed ... working as we speak, as i needed to fix merging issues manually

**Comment by stefanb** [comment]
Alright, I see it now, thank you!

**Pull request closed without merging**
