### PR TITLE
donate ribbon

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by pgiraud** [comment]
With this pull request I added a temporary ribbon with a link to donate.hotosm.org.
To be removed when the fund raising is finished.

**Comment by russdeffner** [comment]
@pgiraud thanks, looks great - does a bit of 'flashing' for me when I first land on the dev site.

**Comment by pgiraud** [comment]
This has nothing to do with what I propose here.
I don't know who did the modification on the dev instance.

**Comment by dodobas** [comment]
@pgiraud that one is mine, as @TylerRadford suggested, it's supposed to go live very soon

**Comment by pgiraud** [comment]
This is a good initiative.
I suppose that it doesn't deserve a pull request.

**Comment by dodobas** [comment]
@pgiraud as you said, 'remove after campaign', so i did not really wanted to create a PR, 

I've combined both banners, so that flashy one is only shown once per 'session' and ribbon is permanent

**Comment by pgiraud** [comment]
Replaced by #710. Closing.

**Pull request closed without merging**
