### PR TITLE
Check for messages

### PR DESCRIPTION
**Pull request by pgiraud**
#791 should be merged first.

With this pull request I tried to make the unread message notifications more obvious by:
 - using a shaking popover which is more visible than the pulse effect,
 - checking for new message every 30s and alerting the user when he gets new messages.

Hopefully the users at a mapathon will see the messages from validators earlier.

### CODE REVIEW

**Comment by pgiraud** [comment]
Still a work in progress.

**Comment by pgiraud** [comment]
This is now ready for review.

This is how it looks.
capture d ecran 2016-05-01 a 21 24 32

**Comment by ethan-nelson** [comment]
This worked great for me! 

As a side note, do you think it may be worth adding this kind of alert (maybe not the popover as well) for when a task lock is about to expire?

**Comment by pgiraud** [comment]
@ethan-nelson Indeed I intended to do the same for automatic unlock notifications.

**Pull request merged**
