### PR TITLE
allow setting in local.ini to over-ride default interval for task expiry check

### PR DESCRIPTION
**Pull request by batpad**
Refs #879 

cc @ethan-nelson @bgirardot @pgiraud 

Have added the ability to over-ride this in `local.ini` and added some documentation to README.md.

I am not sure the best approach to test custom settings. If someone has some advice on this, happy to work on it.

Also, am not tied to the name - if anyone has a better idea than `check_expiration_interval`, let me know, happy to change.

Thank you!

### CODE REVIEW

**Comment by batpad** [comment]
I'm seeing some `flake8` errors causing tests to fail, but the relevant lines that are failing are not things I have added with this PR, so not sure what to do :-)

**Comment by pgiraud** [comment]
Hum weird. Looks like someone merged a pull request without taking the travis checks into account.

**Comment by pgiraud** [comment]
I created a new pull request https://github.com/hotosm/osm-tasking-manager2/pull/898 for what actually looks like new syntax rules.

**Comment by pgiraud** [comment]
@batpad Can you please rebase your branch onto master?

**Comment by pgiraud** [comment]
This looks good to me.

**Pull request merged**
