### PR TITLE
Fixes for #640 and #642, bootstrap locale fix and start.mako localization

### PR DESCRIPTION
**Pull request by milovanderlinden**

### CODE REVIEW

**Comment by pgiraud** [comment]
I'm sorry to be picky but I would have preferred 2 different pull requests.

**Comment by milovanderlinden** [comment]
Ok, will create them

**Comment by pgiraud** [comment]
@milovanderlinden I'm so sorry.
Thanks for your contribution.
And once again, don't hesitate to work with branches.

**Comment by milovanderlinden** [comment]
No problem, every community has its own way of working, I am eager to adapt
and make it convenient for you to accept good quality pull-requests.

2015-06-09 16:59 GMT+02:00 Pierre GIRAUD <notifications@github.com>:

> @milovanderlinden <https://github.com/milovanderlinden> I'm so sorry.
> Thanks for your contribution.
> And once again, don't hesitate to work with branches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hotosm/osm-tasking-manager2/pull/643#issuecomment-110393231>
> .
>



-- 
 [image: http://www.dogodigi.net] <http://www.dogodigi.net>
*Milo van der Linden*
web: dogodigi <http://www.dogodigi.net>
tel: +31-6-16598808

**Pull request closed without merging**
