### PR TITLE
Message all contributors

### LINKED ISSUE #719: Contact all contributors to a project button
I would like a way to send a message (TM internal, or opt-in'ed email (I know TM doesn't sent emails)) to all the users who have contributed to a project. For now I think the list of people who are in the "stats" tab would be enough, knowing that eventually validators will be listed there :)

Some use cases are to thank people, let them know of changes to instructions, or in my current case, let them know we are creating new TM projects related to the project they have already contributed to and the current project will be archived.

### PR DESCRIPTION
**Pull request by ethan-nelson**
This will fix #719, which requested functionality to message all contributors of a task. The functionality is mostly based on recycled code already existing in the project.

I'm opening the pull request to check functionality and get any feedback. I still need to write a test or two to cover the functionality before it will be good to go.

### CODE REVIEW

**Comment by ethan-nelson** [comment]
I went ahead and added a few tests for this functionality. Things to note:

* An unrelated test (to check for message delivery of an `@` mention) was broken after I added these tests because mine sent additional messages. So I modified that test to look for the difference in message number as opposed to counting == 1.
* The functionality of messaging everyone on a project only applies to people who have marked a task as 'done'. That is because I use the function from in the stats tab that counts the number of tiles people have marked done to determine message recipients. 

Please let me know feedback and/or comments!

**Comment by ethan-nelson** [comment]
Menu
Filled in prompt
Resulting message

**Comment by pgiraud** [comment]
It looks good to me.

I was not completely happy with the UI so I allowed myself some changes (remove some unrequired text, reorganized elements, added text helpers css rules). See https://github.com/pgiraud/osm-tasking-manager2/commit/266a7abe9e6168e7859e383ad68f058e94c9120c

capture d ecran 2016-04-24 a 19 14 03


If I understand well you got inspired by the "invalidate all" feature. I'm not super happy with the UI of it by the way, and would like to enhance it a bit.

If you're happy with my changes, please cherry-pick the commit and squash it in yours.

**Comment by ethan-nelson** [comment]
Alright, great...I"ll look at your modifications. Yes, I recycled some of the code from the invalidate and am not a big fan of the modal either.

**Comment by pgiraud** [comment]
Can you please squash/fixup your commits into one?

**Comment by pgiraud** [comment]
Nice work. I'm sure project managers will appreciate. You can merge.

**Comment by ethan-nelson** [comment]
Great!

**Comment by mnoblecourt** [comment]
Thanks @ethan-nelson and @pgiraud, this looks exactly like what we were looking for! Great job.

**Pull request merged**
