### PR TITLE
Language menu shows corresponding flags (fixes #608) - second try

### LINKED ISSUE #608: Full language name is language picker drop-down menu
Currently the language picker drop-down menu just lists short "names" for the languages (eg. en, de, fr, etc...). I propose we make it look better and more user-friendly by using the language files. Menu should  show "English, Deutsch, Francais, Espanol, etc.." instead of "en, de, fr, etc...".

### PR DESCRIPTION
**Pull request by skalca**
Because I am still new to git I was unable to revert existing branch back two commits. I have created a new branch and commited only changes that show full language names (without flags).

I did not include Slovenian language, because translations where not yet merged into master. When they are, we need to change README file. (I can do this, right? - if I first pull down branch, add changes to README and commit back?)

### CODE REVIEW

**Comment by skalca** [comment]
Maybe @stefanb can add Slovenian option to language variables in development.ini.

**Comment by stefanb** [comment]
Not sure how would that be related to Slovenian, as #574 is still open?

If this gets accepted before #574, I will update my patch to accomodate for the new configuration requirements - same is valid for the opposite, if #574 is accepted before this one, then Slovenian language should be added here (after git merge/rebase in both cases)

**Comment by skalca** [comment]
Aha ok. As I said. Still new to git and all this pull request stuff.

**Comment by pgiraud** [comment]
@skalca test fail. Do you think you are able to fix the errors?

**Comment by skalca** [comment]
I will check it at home in the afternoon. No problem.

**Comment by pgiraud** [comment]
@skalca I took the liberty to continue your work in #651. I removed the flags and fixed the tests. Closing.

Please feel free to reopen a new issue or pull request to start discussion on the flags images (with screenshots for example).

**Comment by skalca** [comment]
Much obliged. I have fixed pull request at work and was just about to sumbit when I saw your msg. It's better that way. You know your way around git and GitHub better than me. I still strugle with git and commits to GitHub - they drive me crazy sometimes. On paper everything about git looks so simple, but in practice it's pain-in-the-a**.
Thanks again.
(Maybe flags bring too much work and setup steps for new-comers, so I propose we leave them out of the project).

**Comment by stefanb** [comment]
Also, country flags do not necessarily represent the languages. Most notably in cases of multilingual countries (eg. Switzerland, Canada, Belgium...) or widely spoken languages (eg. English, German, French...).

**Comment by pierzen** [comment]
+1 
These national flags is not a good way to deal with cultural diversity.

**Pull request closed without merging**
