### PR TITLE
README.md : Making it clear where to put the password

### PR DESCRIPTION
**Pull request by adusca**
When I followed the instructions I got the error: 
FATAL:  password authentication failed for user "www-data"
Then I realized that I had to put my password in the local.ini file and I thought that maybe someone else would also make this mistake.

### CODE REVIEW

**Comment by pyrog** [comment]
:+1: I got the same problem

**Comment by pyrog** [comment]
May be you could update the title of this PR so it will more clear and could be merged?
>  **README.md** : Making it clear where to put the password

**Comment by adusca** [comment]
Done!

**Comment by pgiraud** [comment]
OK.
I wasn't completely happy with this pull request but since it won't have any nasty effect, I can merge it.
Thanks.

**Pull request merged**
