### PR TITLE
Implement project tagging

### PR DESCRIPTION
**Pull request by ethan-nelson**
From #528 (where much of this dev has been discussed--see there for screenshots), #552, #487, and in passing, the need for project tagging is ever-present. This pull request attempts to implement this functionality. The basic idea is as follows.

One or more tags can be assigned to a project, which can then be queried to filter exposed projects. A feature that is included with tags is a "spotlight text" blurb that provides some information about the tag to users. This can be where an activation is described in a little more detail, a requesting agency's efforts are detailed, or the general basis of the task--such as mapping roads versus buildings--can be expounded upon.
### Database backend

A new model is created that stores all project tags and their associated data. Tied to this model is a project tag translation table that stores the spotlight text translations. Another table stores the tag and project relationships.
### View configuration

The tagging view structure mostly follows the licenses. A list of current tags can be accessed via the user menu _if the user is an administrator_. Tags can be created, first filled out with their name and administrator description, and then the spotlight text translations can be added afterwards as they are received.
### Tag assignment

The project editing screen now includes another tab that lists all tags available and associated checkboxes to assign tags to the project. 
### Tag search

Tag searching is available via the url parameter `tags=x+y+z+...`. This structure assumes tags do not have spaces in them (though other characters separating words should be fine, like `-` or `_`).
### Spotlight text display

If one or more tags are passed to the home page, the spotlight text for each tag appears in a well on the right hand side of the screen. This provides a tag-focused display when searching tags.
### Especially need input on:
- How do we expose the tag search to users?
- Is the spotlight text unwanted?
### TBImplemented:
- [x] Tag search interface
- [x] Write tests
- [ ] Include project translation table in alembic upgrade/downgrade
- [x] Refine database query if necessary

### CODE REVIEW

**Comment by ethan-nelson** [comment]
Latest branch push features improvements in search over the last push whereby tags are now recognized by search terms that start with `tag:`. These can either be typed manually or eventually added by tags displayed in places. That resolves some of the issues with implementing a search and having a separate clunky database query. Unfortunately, I'm still struggling to find a good way to pass on the ids of the tags recognized post-query so that the spotlight text can be rendered. Or maybe we don't even want that.

**Comment by ethan-nelson** [comment]
closing for now

**Comment by pgiraud** [comment]
I'll give this a second try. As proposed to Blake by email, I'll probably rename "tag" to "label" since to me tags are like keywords, ie. not defined in advance and freely written by users. We are closer to what github calls labels here.

**Comment by ethan-nelson** [comment]
Okay, great. 

Actually, it may make more sense for me to split this up into incremental changes for different aspects 1) because it's a lot of changes and 2) some of this has been altered beyond the current state of this PR for https://github.com/ethan-nelson/osm-tasking-manager2/tree/project-highlight (which stemmed from this but modified some of the features, e.g. for an overhauled front page).

Would that work for you?

**Comment by pgiraud** [comment]
Good to know that you also worked on the home page.
I will compare this to what I did last year after Nitika's internship. https://github.com/pgiraud/osm-tasking-manager2/tree/programs (not finished)

**Comment by pgiraud** [comment]
@ethan-nelson I reworked on your pull request and simplified it to get something working quickly with labels. Search has been enhanced and spaces are allowed in labels (previously tags).
https://github.com/pgiraud/osm-tasking-manager2/tree/project-tagging
I'll show a demo early next week.

**Pull request closed without merging**
