### PR TITLE
Use https URLs for openstreetmap.org oauth and api endpoints

### PR DESCRIPTION
**Pull request by grischard**
The oauth endpoint must change soon or logins will break. The rest is just good practice.

### CODE REVIEW

**Comment by bgirardot** [comment]
@grischard Hi thank you very much for the PR, just wondering why you closed it.

Cheers,
blake

**Comment by grischard** [comment]
Hi @bgirardot. I realised the oauth url [had actually already been changed in 2015](https://github.com/hotosm/osm-tasking-manager2/commit/ce7552004130e8673edeabbf6b9e3341fa282be7), so I didn't want to bother anyone with non-urgent fixes. I'm happy resubmitting a separate PR that converts all http://openstreetmap.org links to htps if you'd like?

Cheers,

Guillaume

**Comment by bgirardot** [comment]
I guess I need to look a little further into it because we did just get a notice that the TM2 was using regular http, for oauth, but maybe that is for installations that are not up to date.

Either way, thank you very much for the PR, it is much appreciated. I amy end up re-opening it so we can merge it in.

**Comment by grischard** [comment]
Yes, that is indeed for installations that haven't been updated since 2015.

**Comment by ethan-nelson** [comment]
For older installations, you may need to update your httplib2 module if you're getting handshake errors.

**Pull request closed without merging**
