### PR TITLE
Adding experienced mapper role

### PR DESCRIPTION
**Pull request by pgiraud**
This pull request introduces a new "experienced mapper" role. This new role gives some users the permissions to contribute to projects "requiring experienced mappers".

Project manager can configure the projects to require this role.

screenshot from 2017-01-20 16 46 58

Users who don't have the required role can still access the tasks but can't press the "start mapping" button. Instead they are proposed to contact the author if they think they deserve the "experienced mapper" role.

screenshot from 2017-01-20 16 44 38

Clicking on the link redirects them to the message form on the OSM website so that projects manager can receive an email until we can manage it internally in the tasking manager.

### CODE REVIEW

**Comment by bgirardot** [comment]
@pgiraud Where is the link to the demo or staging of this pr?

**Comment by pgiraud** [comment]
http://tasks-hotosm.dev.sig.cloud.camptocamp.net/experienced

**Comment by pgiraud** [comment]
> I am still not happy with the error message when it links to OSM to send a message, but it might actually be a good thing in that it focuses the users attention.

Would a different wording make you happier?

**Comment by bgirardot** [comment]
No, it is just really jarring to be met with an error dialog.

Can we just give them a blank email message?

Like I said, not sure which is better. This way at least the link to their osm user gets in there. Which would probably be on the email anyway..... 

Either way. 

Just taking them to the project manager's osm page is probably not enough, should not make people figure out they have to click 'send message' if we can avoid it.

**Comment by pgiraud** [comment]
I agree with.
I think I have an other idea to prevent this. What I can try is to have the message being sent silently in background and then show a message dialog that the message has been sent.
I'll try this as soon as I can.

**Comment by pgiraud** [comment]
There were modifications on the OSM website yesterday regarding the message API.
Previously when opening the "new/message" page, if one provided both "title" and "body" using params in the URL, the message was sent directly without any action from the user.
It was actually a security issue. I reported this and it was fixed very quickly.

Now it's possible to open the page and pre-fill both "title" and "body". It allows the user to read the message to be sent before submission.

Merging.

**Pull request merged**
